/* New defaults/session separation, controls and paused data IO, owned fixtures only. */
static void test_flexible_controls(void) {
    TimerSettings saved=settings;
    settings.enable_clock_sound=settings.enable_completion_sound=settings.reminder_mode=0;
    settings.enable_micro_break=1;settings.micro_break_interval_minutes=15;settings.micro_break_duration_minutes=1;
    settings.enable_overtime_count_up=1;settings.enable_pomodoro_count=1;settings.long_pomodoro_count=3;
    timer_test_reset();
    start_timer(g_main_hwnd,45,TIMER_LONG_POMODORO);
    int initial=get_today_count_from_storage();
    choose_menu(ID_MENU_ENABLE_OVERTIME);choose_menu(ID_MENU_ENABLE_POMODORO_COUNT);choose_menu(ID_MENU_ENABLE_MICRO_BREAK);
    settings.micro_break_interval_minutes=10;settings.micro_break_duration_minutes=2;settings.long_pomodoro_count=1;
    CHECK(!settings.enable_overtime_count_up && !settings.enable_pomodoro_count && !settings.enable_micro_break,"running settings controls remain usable");
    CHECK(timer_effective_overtime() && timer_effective_count() && session_rules.long_count==3 && micro.interval_seconds==900 && micro.duration_seconds==60,"active focus retains original rule snapshot");
    timer_advance_seconds(g_main_hwnd,900);
    CHECK(is_overtime && micro.phase==MICRO_WAIT_START,"original due rule still enters overtime");
    timer_primary_action(g_main_hwnd);CHECK(remaining_seconds==60,"micro uses parent duration rather than new default");
    timer_stop_action(g_main_hwnd);timer_primary_action(g_main_hwnd);remaining_seconds=1;timer_advance_seconds(g_main_hwnd,1);
    CHECK(get_today_count_from_storage()==initial+3 && is_overtime,"original long count and overtime apply at completion");
    timer_test_reset();start_timer(g_main_hwnd,1,TIMER_LONG_POMODORO);timer_advance_seconds(g_main_hwnd,60);
    CHECK(!is_overtime && get_today_count_from_storage()==initial+3 && !session_rules.valid,"fresh session uses changed count and overtime defaults");
    settings.short_pomodoro_duration=45;
    timer_test_reset();start_timer(g_main_hwnd,45,TIMER_SHORT_POMODORO);remaining_seconds=1920;
    choose_menu(ID_MENU_IDLE_SHORT_POMODORO);
    CHECK(!is_running && timer_ui_resolve().seconds==2700 && micro.source==TIMER_NONE && !session_rules.valid,"running same-type ready selection rebuilds a fresh default");
    micro.source=TIMER_SHORT_POMODORO;micro.phase=MICRO_WAIT_RESUME;micro.frozen_seconds=1920;
    choose_menu(ID_MENU_IDLE_SHORT_POMODORO);
    CHECK(micro.source==TIMER_NONE && timer_ui_resolve().seconds==2700,"same frozen ready selection intentionally resets to default too");
    settings.default_pomodoro_is_long=1;choose_menu(ID_MENU_DEFAULT_LONG_POMODORO);
    CHECK(timer_ui_resolve().mode==TIMER_SHORT_POMODORO,"repeat default selection does not overwrite explicit ready type");
    choose_menu(ID_MENU_DEFAULT_SHORT_POMODORO);choose_menu(ID_MENU_DEFAULT_LONG_POMODORO);
    CHECK(timer_ui_resolve().mode==TIMER_SHORT_POMODORO,"changed default type does not overwrite manual selection");
    timer_test_reset();settings.enable_pomodoro_count=1;start_timer(g_main_hwnd,0,TIMER_COUNT_UP);
    int threshold=(settings.short_pomodoro_duration*60);
    timer_advance_seconds(g_main_hwnd,threshold);
    CHECK(timer_correct_today_count(g_main_hwnd,10) && get_today_count_from_storage()==10,"running manual total is applied immediately");
    CHECK(remaining_seconds==threshold,"manual count correction preserves timer and processed thresholds");
    timer_advance_seconds(g_main_hwnd,threshold);
    CHECK(get_today_count_from_storage()==10,"count-up never adds to corrected total");
    choose_menu(ID_MENU_ENABLE_POMODORO_COUNT);
    CHECK(!settings.enable_pomodoro_count && timer_effective_count(),"new disabled default does not alter current count-up");
    choose_menu(ID_MENU_RESET_COUNT);
    CHECK(get_today_count_from_storage()==0,"running clear preserves high-water mark");
    choose_menu(ID_MENU_PAUSE_RESUME);
    CHECK(!is_running && is_paused && !timer_setting_locked(ID_MENU_IMPORT_DATA) && !timer_setting_locked(ID_MENU_DATA_LOC_CUSTOM),"paused data actions are enabled");
    wchar_t package[MAX_PATH],settings_file[MAX_PATH],output[MAX_PATH],target[MAX_PATH];
    wcscpy(test_io_root,g_data_dir);
    swprintf(package,MAX_PATH,L"%ls\\input",test_io_root);CreateDirectoryW(package,NULL);
    swprintf(settings_file,MAX_PATH,L"%ls\\pomodoro_settings.json",package);
    write_test_json(settings_file,"{\"pomodoro_duration\":12,\"pomodoro_count\":0,\"short_pomodoro_duration\":1,\"enable_pomodoro_count\":0,\"enable_overtime_count_up\":0,\"enable_completion_sound\":0,\"show_completion_dialog\":0}");
    test_io_active=1;wcscpy(test_io_folder,package);
    int elapsed=remaining_seconds;
    CHECK(import_data_from_folder(g_main_hwnd),"real paused import succeeds against owned package");
    CHECK(current_timer_mode==TIMER_COUNT_UP && is_paused && remaining_seconds==elapsed && timer_effective_count(),"import retains paused progress rules and threshold");
    swprintf(target,MAX_PATH,L"%ls\\moved",test_io_root);
    CHECK(switch_data_location(g_main_hwnd,DATA_LOC_CUSTOM,target),"real paused migration succeeds with registry writes intercepted");
    CHECK(is_paused && remaining_seconds==elapsed && session_rules.valid,"migration retains paused runtime");
    choose_menu(ID_MENU_PAUSE_RESUME);
    CHECK(timer_setting_locked(ID_MENU_IMPORT_DATA) && timer_setting_locked(ID_MENU_DATA_LOC_CUSTOM),"actual running blocks import and migration only");
    swprintf(output,MAX_PATH,L"%ls\\export",test_io_root);CreateDirectoryW(output,NULL);wcscpy(test_io_folder,output);
    CHECK(export_data_to_folder(g_main_hwnd) && is_running && current_timer_mode==TIMER_COUNT_UP,"real export during running leaves timer active");
    reset_defaults_keep_data();timer_apply_live_preferences();
    CHECK(is_running && remaining_seconds==elapsed,"reset defaults does not reset runtime");
    test_io_active=0;timer_test_reset();settings=saved;save_settings();
    printf("FLEXIBLE_CONTROLS_TEST: %s (%d failures)\n",failures ? "FAIL" : "PASS",failures);
}
