/* Only v2.5.34 ready transitions and separator geometry, not old suites. */
static void test_ready_states(void) {
    TimerSettings saved = settings;
    FullscreenView view;
    settings.enable_clock_sound = settings.enable_completion_sound = settings.reminder_mode = 0;
    settings.enable_pomodoro_count = 0;
    settings.enable_micro_break = 1; settings.micro_break_interval_minutes = 15; settings.micro_break_duration_minutes = 1;
    settings.enable_overtime_count_up = 0;
    timer_test_reset();
    start_timer(g_main_hwnd, 0, TIMER_SHORT_POMODORO); timer_advance_seconds(g_main_hwnd, 0);
    TimerUiView ready = timer_ui_resolve();
    CHECK(ready.mode == timer_next_mode(TIMER_SHORT_POMODORO) && ready.state == TIMER_UI_READY && ready.seconds == timer_ui_duration(ready.mode), "completion displays next preset ready");
    fs_read_timer_view(&view); CHECK(wcsstr(view.status, L" · 未开始") != NULL, "completion is not a persistent display status");
    TimerMode target = ready.mode; int seconds = ready.seconds;
    timer_primary_action(g_main_hwnd);
    CHECK(current_timer_mode == target && remaining_seconds == seconds && is_running, "start matches displayed ready target and time");
    timer_test_reset();
    start_timer(g_main_hwnd, 45, TIMER_SHORT_POMODORO); timer_advance_seconds(g_main_hwnd, 900);
    ready = timer_ui_resolve();
    CHECK(ready.mode == TIMER_MICRO_BREAK && ready.state == TIMER_UI_READY && ready.seconds == 60 && remaining_seconds == 1800, "micro due presents its preset while main time is retained");
    CHECK(timer_ui_can_start() && !timer_ui_can_pause() && !timer_ui_can_end(), "all ready states expose only start");
    refresh_timer_icon_by_state(g_main_hwnd);
    CHECK(!wcscmp(last_text, L"\u25BA"), "micro ready uses the same idle tray icon as other modes");
    timer_primary_action(g_main_hwnd); timer_advance_seconds(g_main_hwnd, 10); timer_stop_action(g_main_hwnd);
    ready = timer_ui_resolve();
    CHECK(ready.mode == TIMER_SHORT_POMODORO && ready.seconds == 1800 && ready.state == TIMER_UI_READY && !is_running, "early micro end does not auto-run focus");
    timer_advance_seconds(g_main_hwnd, 100);
    CHECK(micro.frozen_seconds == 1800 && timer_ui_resolve().seconds == 1800, "ready focus does not consume frozen time");
    settings.short_pomodoro_duration = 50;
    CHECK(timer_ui_resolve().seconds == 1800, "changed default cannot replace frozen ready focus");
    timer_primary_action(g_main_hwnd);
    CHECK(current_timer_mode == TIMER_SHORT_POMODORO && remaining_seconds == 1800 && is_running, "ready focus starts from original type and exact time");
    timer_test_reset();
    settings.enable_overtime_count_up = 1;
    start_timer(g_main_hwnd, 45, TIMER_SHORT_POMODORO); timer_advance_seconds(g_main_hwnd, 902);
    timer_stop_action(g_main_hwnd);
    CHECK(!is_overtime && !is_running && micro.phase == MICRO_WAIT_START && remaining_seconds == 1800 && micro.frozen_seconds == 1800, "ending due overtime preserves the original frozen main time");
    timer_primary_action(g_main_hwnd); timer_advance_seconds(g_main_hwnd, 63);
    CHECK(is_overtime && timer_ui_can_end(), "expired micro overtime has an end operation");
    choose_menu(ID_MENU_PAUSE_RESUME); choose_menu(ID_MENU_STOP);
    ready = timer_ui_resolve();
    CHECK(ready.mode == TIMER_SHORT_POMODORO && ready.seconds == 1800 && ready.state == TIMER_UI_READY && !is_overtime && !is_running, "paused micro overtime ends to frozen focus ready");
    choose_menu(ID_MENU_IDLE_CUSTOM);
    CHECK(micro.source == TIMER_NONE && timer_ui_resolve().mode == TIMER_CUSTOM && !is_running, "explicit ready mode choice abandons old context without starting");
    timer_test_reset();
    start_timer(g_main_hwnd, 0, TIMER_CUSTOM); timer_advance_seconds(g_main_hwnd, 0); timer_stop_action(g_main_hwnd);
    ready = timer_ui_resolve();
    CHECK(ready.mode == TIMER_CUSTOM && !is_overtime && !is_running && ready.state == TIMER_UI_READY, "ordinary overtime ends to next ready too");
    timer_primary_action(g_main_hwnd); CHECK(current_timer_mode == TIMER_CUSTOM && is_running, "ordinary next ready starts correctly");
    timer_test_reset();
    HDC dc = CreateCompatibleDC(NULL);
    const wchar_t *fonts[] = {L"Segoe UI", L"Microsoft YaHei UI", L"Consolas"};
    int sizes[] = {12, 31, 64}; int i, j;
    for(i=0;i<3;++i) for(j=0;j<3;++j) {
        HFONT font = CreateFontW(-sizes[j],0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,ANTIALIASED_QUALITY,DEFAULT_PITCH,fonts[i]);
        HGDIOBJ previous = SelectObject(dc,font);
        RECT bounds = {-100,0,1100,300};
        FullscreenStatusLayout layout = fs_status_layout(dc,bounds,L"超时正计时 · 暂停");
        CHECK(layout.split && abs(2*layout.dot+layout.dot_width-(bounds.left+bounds.right)) <= 1, "separator center is stable across fonts sizes and offset bounds");
        CHECK(layout.left < layout.dot && layout.right > layout.dot+layout.dot_width, "mode and state flank the separator");
        layout = fs_status_layout(dc,bounds,L"短番茄钟");
        CHECK(!layout.split, "plain mode retains whole-line centering");
        SelectObject(dc,previous);DeleteObject(font);
    }
    settings.fullscreen_show_signature = 0; settings.fullscreen_show_text = 1;
    fs_read_timer_view(&view); wcscpy(view.status,L"超时正计时 · 暂停");
    RECT panel_bounds = {0,0,240,400};
    HDC window_dc = GetDC(g_main_hwnd);
    HBITMAP bitmap = CreateCompatibleBitmap(window_dc,240,400); ReleaseDC(g_main_hwnd,window_dc); HGDIOBJ old_bitmap=SelectObject(dc,bitmap);
    fs_draw_view(dc,panel_bounds,&view,0);
    SelectObject(dc,old_bitmap);DeleteObject(bitmap);DeleteDC(dc);
    settings = saved;
    printf("READY_STATE_TEST: %s (%d failures)\n",failures ? "FAIL" : "PASS",failures);
}
